# Generated by Django 6.1 on 2026-08-29 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Consorcio',
                'verbose_name_plural': 'Consorcios',
            },
        ),
        migrations.CreateModel(
            name='UnidadFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.propietario')),
            ],
            options={
                'verbose_name': 'Unidad Funcional',
                'verbose_name_plural': 'Unidades Funcionales',
            },
        ),
    ]
