# Generated by Django 6.1 on 2026-09-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='CUIT')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('calle', models.CharField(max_length=150)),
                ('altura', models.PositiveIntegerField()),
                ('codigo_postal', models.IntegerField(verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'Consorcio',
                'verbose_name_plural': 'Consorcios',
            },
        ),
        migrations.CreateModel(
            name='UnidadFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio')),
            ],
            options={
                'verbose_name': 'Unidad Funcional',
                'verbose_name_plural': 'Unidades Funcionales',
            },
        ),
    ]
