# Generated by Django 6.1 on 2026-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consorcio',
            name='direccion',
            field=models.CharField(max_length=255, unique=True, verbose_name='Dirección'),
        ),
    ]
