# Generated by Django 6.1 on 2026-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='clave_suterh',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Clave SUTERH'),
        ),
    ]
