# Generated by Django 6.1 on 2026-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0003_consorcio_clave_suterh'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfuncional',
            name='departamento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='unidadfuncional',
            name='piso',
            field=models.PositiveIntegerField(default=1, verbose_name='Piso'),
            preserve_default=False,
        ),
    ]
