# Generated by Django 6.1 on 2026-09-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0004_unidadfuncional_departamento_unidadfuncional_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfuncional',
            name='coeficiente_a',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Coeficiente A (General)'),
        ),
        migrations.AddField(
            model_name='unidadfuncional',
            name='coeficiente_b',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Coeficiente B (Parcial)'),
        ),
        migrations.AddField(
            model_name='unidadfuncional',
            name='coeficiente_c',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Coeficiente C (Fondo de Reserva)'),
        ),
    ]
