# Generated by Django 6.1 on 2026-09-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0005_unidadfuncional_coeficiente_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadfuncional',
            name='coeficiente_a',
        ),
        migrations.RemoveField(
            model_name='unidadfuncional',
            name='coeficiente_b',
        ),
        migrations.RemoveField(
            model_name='unidadfuncional',
            name='coeficiente_c',
        ),
        migrations.AlterField(
            model_name='unidadfuncional',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_funcionales', to='consorcios.consorcio'),
        ),
        migrations.CreateModel(
            name='GrupoProrrateo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo/Columna')),
                ('codigo', models.CharField(help_text='Ej: A, B, C, PISCINA', max_length=10, verbose_name='Código / Identificador')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_prorrateo', to='consorcios.consorcio')),
            ],
            options={
                'verbose_name': 'Grupo de Prorrateo',
                'verbose_name_plural': 'Grupos de Prorrateo',
                'unique_together': {('consorcio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='CoeficienteUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Porcentaje / Coeficiente')),
                ('unidad_funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes', to='consorcios.unidadfuncional')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes_uf', to='consorcios.grupoprorrateo')),
            ],
            options={
                'verbose_name': 'Coeficiente UF',
                'verbose_name_plural': 'Coeficientes UF',
                'unique_together': {('unidad_funcional', 'grupo')},
            },
        ),
    ]
