# Generated by Django 6.1 on 2026-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0006_remove_unidadfuncional_coeficiente_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='horario_atencion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Horario de atención'),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='localidad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Localidad'),
        ),
    ]
