# Generated by Django 6.1 on 2026-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0007_consorcio_horario_atencion_consorcio_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadfuncional',
            name='alicuota',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje que le corresponde a esta UF sobre el total del consorcio.', max_digits=6, verbose_name='Alícuota (%)'),
        ),
        migrations.AlterField(
            model_name='coeficienteuf',
            name='porcentaje',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Porcentaje / Coeficiente'),
        ),
    ]
