# Generated by Django 6.1 on 2026-10-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0008_unidadfuncional_alicuota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('cargo', models.CharField(help_text='Ej: Encargado, Portero, Limpieza', max_length=100, verbose_name='Cargo')),
                ('tipo_contratacion', models.CharField(choices=[('directo', 'Relación de dependencia'), ('tercerizado', 'Tercerizado')], default='directo', max_length=20, verbose_name='Tipo de contratación')),
                ('empresa_tercerizada', models.CharField(blank=True, default='', max_length=150, verbose_name='Empresa tercerizada')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='consorcios.consorcio')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
