# Generated by Django 6.1 on 2026-10-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0011_rubro_grupoprorrateo_rubro'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupoprorrateo',
            unique_together={('consorcio', 'rubro', 'codigo')},
        ),
    ]
