# Generated by Django 6.1 on 2026-10-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0012_alter_grupoprorrateo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoprorrateo',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='consorcios.rubro'),
        ),
    ]
