# Generated by Django 6.1 on 2026-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_alter_consorcio_direccion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='consorcios',
            field=models.ManyToManyField(related_name='administradores', to='consorcios.consorcio'),
        ),
    ]
