# Generated by Django 6.1 on 2026-09-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0005_unidadfuncional_coeficiente_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('ORDINARIO', 'Ordinario'), ('EXTRAORDINARIO', 'Extraordinario')], default='ORDINARIO', max_length=20, verbose_name='Tipo de Gasto')),
                ('grupo', models.CharField(choices=[('A', 'Grupo A (General)'), ('B', 'Grupo B (Parcial)'), ('C', 'Grupo C (Fondo de Reserva)')], default='A', max_length=1, verbose_name='Grupo/Coeficiente')),
                ('periodo', models.CharField(help_text='Formato AAAA-MM (ej: 2026-03)', max_length=7, verbose_name='Período Imputado')),
                ('fecha_comprobante', models.DateField(verbose_name='Fecha del Comprobante')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='consorcios.consorcio')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato AAAA-MM', max_length=7, verbose_name='Período Liquidado')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento_1', models.DateField(verbose_name='Primer Vencimiento')),
                ('total_ordinario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_extraordinario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cerrada', models.BooleanField(default=False, verbose_name='¿Cerrada?')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='consorcios.consorcio')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'unique_together': {('consorcio', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacionUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ordinario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_extraordinario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unidad_funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.unidadfuncional')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_uf', to='gastos.liquidacion')),
            ],
            options={
                'verbose_name': 'Detalle Expensa por UF',
                'verbose_name_plural': 'Detalles Expensas por UF',
            },
        ),
    ]
