# Generated by Django 6.1 on 2026-09-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0006_remove_unidadfuncional_coeficiente_a_and_more'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(max_length=200, verbose_name='Concepto del Gasto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='consorcios.grupoprorrateo', verbose_name='Columna / Grupo de Prorrateo'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('ordinario', 'Ordinario'), ('extraordinario', 'Extraordinario')], default='ordinario', max_length=20, verbose_name='Tipo de Gasto'),
        ),
    ]
