# Generated by Django 6.1 on 2026-09-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gasto_concepto_alter_gasto_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
    ]
