# Generated by Django 6.1 on 2026-09-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_liquidacion_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='subtipo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subtipo / Rubro'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='datos_administracion',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
