# Generated by Django 6.1 on 2026-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_liquidacion_borradores_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
    ]
