# Generated by Django 6.1 on 2026-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_alter_liquidacion_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='subtipo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Subtipo / Rubro'),
        ),
    ]
