# Generated by Django 6.1 on 2026-10-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_gasto_subtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacionuf',
            name='alicuota',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Alícuota aplicada (%)'),
        ),
    ]
