# Generated by Django 6.1 on 2026-10-03 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_gasto_modo_reparto_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('comprobante', models.FileField(upload_to='comprobantes_pago/', verbose_name='Comprobante de transferencia')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle_liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gastos.detalleliquidacionuf')),
            ],
            options={
                'verbose_name': 'Pago de Expensa',
                'verbose_name_plural': 'Pagos de Expensas',
            },
        ),
    ]
