# Generated by Django 6.1 on 2026-10-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='notas_admin',
            field=models.TextField(blank=True, default='', verbose_name='Notas del Administrador'),
        ),
    ]
