# Generated by Django 6.1 on 2026-10-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_remove_gasto_modo_reparto_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='subtipo',
        ),
    ]
